### ISSUE TITLE
Invalid image name when the image tag is integer

### ISSUE THREAD

**Issue by dwiajik** [astronomer/airflow-chart#217] opened 2021-05-04 03:31 UTC
I used commit short SHA to tag image. When the image tag is integer the image tag being passed to kubernetes resources are invalid.

Example:

I have image tag `5060547`

helm template
```
helm template astronomer-main astronomer/airflow --set images.airflow.tag=5060547
```

Result:
```
...
      containers:
        - name: create-user
          image: quay.io/astronomer/ap-airflow:%!s(int64=5060547)
...
```

I think it is because of this helper implementation https://github.com/astronomer/airflow-chart/blob/90b09113783c609e08b191f5dc313730a0e7dabe/templates/_helpers.yaml#L113-L115

**Comment by danielhoherd** [comment] 2024-02-08 01:40
Interesting edge case! I was able to reproduce this almost 3 years later:

```
$ helm template . --set airflow.images.airflow.tag=5060547 | grep ap-airflow
Error: values don't meet the specifications of the schema(s) in the following chart(s):
airflow:
- images.airflow.tag: Invalid type. Expected: [string,null], given: integer
```

Thanks for the report @dwiajik and I am sorry for getting back to you so late! I just realized I was not watching all activity on this repository 🤦‍♂️

**Comment by danielhoherd** [comment] 2024-03-08 20:57
This is actually a problem with the OSS airflow chart. I have expanded airflow-chart 1.11.1 and run:

```
$ helm template . --set images.airflow.tag=5060547
Error: values don't meet the specifications of the schema(s) in the following chart(s):
airflow:
- images.airflow.tag: Invalid type. Expected: [string,null], given: integer
```

CC @jedcunningham

**Comment by danielhoherd** [comment] 2024-03-08 21:08
I found the fix for the shell. `--set-string images.airflow.tag=5060547` It seems like we should be using this in all cases, so we can fix that on our end. I can't imagine a place where we'd want input value to be interpreted as an integer. This is definitely a limitation of the shell's dynamic typing and helm's implementation that attempts to add types. It seems unintuitive to me.

**Comment by danielhoherd** [comment] 2024-03-08 21:53
I think there's probably not a bug here. With yaml, the values should be specified as strings, because that's what they are, so something like:

```yaml
airflow:
  images:
    airflow:
      tag: "5060547"
```

And on the CLI users should be using `--set-string`, because the data they are giving is a string, not an integer.

Other than that, the only thing I can think of to do is educate people on how helm handles types.

**Comment by jedcunningham** [comment] 2024-03-09 06:07
I'm not sure where we'd place anything in docs where folks would find it when they hit it. I also think the schema check provides a decent error message now. I'm not sure we should do anything for this. Maybe now search engines will find this issue if folks look that way 🤷.

**Comment by danielhoherd** [comment] 2024-03-12 17:04
@jedcunningham I agree. I think we can close this. @dwiajik if you want to respond about this in the thread feel free, though since I took so long to respond I would not be surprised if it's not relevant anymore. I'm going to go ahead and close this one for now.

**Closed by danielhoherd** 2024-03-12 17:04 UTC

**Comment by Eroyi** [comment] 2025-12-17 08:54
> Interesting edge case! I was able to reproduce this almost 3 years later:

Funny, I just hit this issue.

This is an interesting breakdown of how Gitlab generate its `COMMIT_ID`: https://medium.com/@jonathan_finch/git-commit-hash-number-theory-770f67ec492d

Because in SHA1, every character in hexadecimal has 16 options, and 10 of 16 are integers, that makes around `(10÷16)⁸×100 ≈ 2.328%` of the probability you will get a full digit, short, 8 letters `COMMIT_ID`:

Congrats, you won a lottery on Gitlab.
